version: "3"
services:
  ssr:
    container_name: blog-web
    build: .
    volumes:
      - .:/usr/src/blog/
      - /usr/src/blog/node_modules
    working_dir: /usr/src/blog
    command: npm run pm2
    ports:
      - "80:3000"
